# Generated by Django 4.1.7 on 2023-03-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_thumbnailimage_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnailimage',
        ),
    ]
